### ISSUE TITLE
(node) warning: possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by franky-continu** [winfinit/mongodb-prebuilt#11]
My tests which use Mockgoose just downloaded (because of a docker rebuild) latest version and now I get this error

``` sh
(node) warning: possible EventEmitter memory leak detected. 11 uncaughtException listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.addListener (events.js:239:17)
    at start (/Users/franky/Workspace/continu/continu-api/node_modules/mongodb-prebuilt/index.js:89:12)
    at Object.start_server (/Users/franky/Workspace/continu/continu-api/node_modules/mongodb-prebuilt/index.js:37:3)
    at start_server (/Users/franky/Workspace/continu/continu-api/node_modules/mockgoose/Mockgoose.js:62:16)
    at EventEmitter.<anonymous> (/Users/franky/Workspace/continu/continu-api/node_modules/mockgoose/Mockgoose.js:67:17)
    at EventEmitter.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at ChildProcess.<anonymous> (/Users/franky/Workspace/continu/continu-api/node_modules/mongodb-prebuilt/index.js:55:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
(node) warning: possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.addListener (events.js:239:17)
    at start (/Users/franky/Workspace/continu/continu-api/node_modules/mongodb-prebuilt/index.js:90:12)
    at Object.start_server (/Users/franky/Workspace/continu/continu-api/node_modules/mongodb-prebuilt/index.js:37:3)
    at start_server (/Users/franky/Workspace/continu/continu-api/node_modules/mockgoose/Mockgoose.js:62:16)
    at EventEmitter.<anonymous> (/Users/franky/Workspace/continu/continu-api/node_modules/mockgoose/Mockgoose.js:67:17)
    at EventEmitter.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at ChildProcess.<anonymous> (/Users/franky/Workspace/continu/continu-api/node_modules/mongodb-prebuilt/index.js:55:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
    1) "before all" hook
```

**Comment by franky-continu** [comment]
I were able to get a work around going.

check [This](https://github.com/mccormicka/Mockgoose/issues/173) at Mockgoose

**Comment by winfinit** [comment]
@franky-continu is this still an issue after latest version of Mockgoose?

**Comment by franky-continu** [comment]
Sorry, forgot to click update. This issue has not been fixed. been fixed in 5.2.2

**Comment by franky-continu** [comment]
This is from right now. It does connects afterwards though. But I had to bump up my tests timeout to 15 seconds.

``` sh
(node) warning: possible EventEmitter memory leak detected. 11 mongoShutdown listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:239:17)
    at EventEmitter.once (events.js:265:8)
    at start (/Users/franky/Workspace/continu/analyze/node_modules/mongodb-prebuilt/index.js:62:11)
    at Object.start_server (/Users/franky/Workspace/continu/analyze/node_modules/mongodb-prebuilt/index.js:44:3)
    at start_server (/Users/franky/Workspace/continu/analyze/node_modules/mockgoose/Mockgoose.js:92:33)
    at EventEmitter.<anonymous> (/Users/franky/Workspace/continu/analyze/node_modules/mockgoose/Mockgoose.js:97:17)
    at EventEmitter.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at Socket.<anonymous> (/Users/franky/Workspace/continu/analyze/node_modules/mongodb-prebuilt/index.js:83:49)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

``` sh
├─┬ mockgoose@5.2.2
│ └─┬ mongodb-prebuilt@4.4.8
...... a ton more here
....... but just wanted to show mockgoose mongodb-prebuilt and mongoose
├── moment@2.11.1
├─┬ mongoose@4.3.6
```

**Comment by franky-continu** [comment]
I think is either the reset of the mongodb-prebuilt or the mongoose version 4.3.6

**Comment by franky-continu** [comment]
After running my tests a couple of times - all good.

I start getting the exception and did ps aux mongo

``` sh
franky           3792   0.7  0.2  2513932  18620 s002  S     6:57PM   0:00.82 /Users/franky/Workspace/continu/analyze/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod --storageEngine ephemeralForTest --port 27025 --dbpath /Users/franky/Workspace/continu/analyze/node_modules/mockgoose/.mongooseTempDB/27025
franky           3915   0.6  0.2  2509156  17784 s002  S     7:00PM   0:00.22 /Users/franky/Workspace/continu/analyze/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod --storageEngine ephemeralForTest --port 27027 --dbpath /Users/franky/Workspace/continu/analyze/node_modules/mockgoose/.mongooseTempDB/27027
franky           3806   0.4  0.2  2513480  18456 s002  S     6:57PM   0:00.76 /Users/franky/Workspace/continu/analyze/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod --storageEngine ephemeralForTest --port 27026 --dbpath /Users/franky/Workspace/continu/analyze/node_modules/mockgoose/.mongooseTempDB/27026
franky           3643   0.2  0.2  2517444  18800 s002  S     6:54PM   0:01.25 /Users/franky/Workspace/continu/analyze/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod --storageEngine ephemeralForTest --port 27021 --dbpath /Users/franky/Workspace/continu/analyze/node_modules/mockgoose/.mongooseTempDB/27021
franky           3664   0.2  0.2  2516536  18556 s002  S     6:55PM   0:01.19 /Users/franky/Workspace/continu/analyze/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod --storageEngine ephemeralForTest --port 27023 --dbpath /Users/franky/Workspace/continu/analyze/node_modules/mockgoose/.mongooseTempDB/27023
franky           2036   0.2  0.2  2513440  15132 s002  S     9:26AM   2:05.00 /Users/franky/Workspace/continu/continu-api/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod --storageEngine ephemeralForTest --port 27017 --dbpath /Users/franky/Workspace/continu/continu-api/node_modules/mockgoose/.mongooseTempDB/27017
franky           3504   0.2  0.2  2517172  19080 s002  S     6:45PM   0:03.19 /Users/franky/Workspace/continu/analyze/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod --storageEngine ephemeralForTest --port 27019 --dbpath /Users/franky/Workspace/continu/analyze/node_modules/mockgoose/.mongooseTempDB/27019
franky           3512   0.1  0.2  2516208  18684 s002  S     6:46PM   0:03.11 /Users/franky/Workspace/continu/analyze/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod --storageEngine ephemeralForTest --port 27020 --dbpath /Users/franky/Workspace/continu/analyze/node_modules/mockgoose/.mongooseTempDB/27020
franky           3931   0.1  0.2  2509156  17872 s002  S     7:00PM   0:00.22 /Users/franky/Workspace/continu/analyze/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod --storageEngine ephemeralForTest --port 27028 --dbpath /Users/franky/Workspace/continu/analyze/node_modules/mockgoose/.mongooseTempDB/27028
franky           3653   0.1  0.2  2516536  18860 s002  S     6:54PM   0:01.25 /Users/franky/Workspace/continu/analyze/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod --storageEngine ephemeralForTest --port 27022 --dbpath /Users/franky/Workspace/continu/analyze/node_modules/mockgoose/.mongooseTempDB/27022
franky           3779   0.1  0.2  2513900  18560 s002  S     6:57PM   0:00.82 /Users/franky/Workspace/continu/analyze/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod --storageEngine ephemeralForTest --port 27024 --dbpath /Users/franky/Workspace/continu/analyze/node_modules/mockgoose/.mongooseTempDB/27024
franky           3497   0.1  0.2  2516208  18816 s002  S     6:45PM   0:03.19 /Users/franky/Workspace/continu/analyze/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod --storageEngine ephemeralForTest --port 27018 --dbpath /Users/franky/Workspace/continu/analyze/node_modules/mockgoose/.mongooseTempDB/27018
franky           3948   0.1  0.2  2509164  17488 s002  S     7:00PM   0:00.16 /Users/franky/Workspace/continu/analyze/node_modules/mongodb-prebuilt/dist/3.2.0/bin/mongod --storageEngine ephemeralForTest --port 27029 --dbpath /Users/franky/Workspace/continu/analyze/node_modules/mockgoose/.mongooseTempDB/27029
franky           4050   0.0  0.0  2434836    760 s002  S+    7:00PM   0:00.00 grep mongo
```

How do I shut it down after I use it?

**Comment by winfinit** [comment]
this was resolved in new releases.
