### ISSUE TITLE
ETIMEDOUT during installing

### ISSUE THREAD

**Issue by thisispax** [winfinit/mongodb-prebuilt#18]
When installing this package I get following message:

```
> node install.js

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 54.230.45.109:443
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1057:14)
```

Running with OSX 10.11.3, Node version 5.7.0, NPM version 3.6.0

**Comment by winfinit** [comment]
@pax1878 is this due to the issue that download doesn't support proxy?

**Comment by thisispax** [comment]
yes, this was before i was looking for the issue myself ;)

thanks!
