### ISSUE TITLE
Error installing mongodb-prebuilt on vagrant machine - Windows 10 Host, Ubuntu 14.04 guest

### ISSUE THREAD

**Issue by tomsitter** [winfinit/mongodb-prebuilt#33]
Hi, I get the following when trying to install mongodb-prebuilt on a vagrant machine.

```
vagrant@vagrant-ubuntu-trusty-64:/var/www/mediamade$ DEBUG=* npm install mongodb-prebuilt --no-bin-links

> mongodb-prebuilt@5.0.6 postinstall /var/www/mediamade/node_modules/mongodb-prebuilt
> node install.js

done
  mongodb-prebuilt installing version: 3.2.0 +0ms
  mongodb-download selected platform linux +2ms
  mongodb-download selected architecture x86_64 +2ms
  mongodb-download selected version: 3.2.0 +1ms
  mongodb-download os dump +6ms { os: 'linux',
  dist: 'Ubuntu Linux',
  codename: 'trusty',
  release: '14.04' }
  mongodb-download selected archive tgz +13ms
  mongodb-download final name: mongodb-linux-x86_64-ubuntu1404-3.2.0.tgz +0ms
  mongodb-download final download URI: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1404-3.2.0.tgz +0ms
  mongodb-download download directory: /var/www/mediamade/node_modules/mongodb-prebuilt +2ms
  mongodb-download download complete path: /var/www/mediamade/node_modules/mongodb-prebuilt/mongodb-download/mongodb-linux-x86_64-ubuntu1404-3.2.0.tgz +0ms
  mongodb-download http opts: +4ms { protocol: 'https:',
  hostname: 'fastdl.mongodb.org',
  path: '/linux/mongodb-linux-x86_64-ubuntu1404-3.2.0.tgz' }
  mongodb-prebuilt archive type selected targz +2m
Killed
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Linux 3.13.0-95-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "mongodb-prebuilt" "--no-bin-links"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! mongodb-prebuilt@5.0.6 postinstall: `node install.js`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the mongodb-prebuilt@5.0.6 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mongodb-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mongodb-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mongodb-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/mediamade/npm-debug.log
```

The --no-bin-links is a requirement due to quirks with being on a Windows filesystem, but hasn't prevented me from installing any other npm modules.

I'm using nodejs v 6.7.0 and npm v3.10.3

Thanks!

**Comment by tomsitter** [comment]
Here is the output from npm-debug.log during the mongodb-prebuilt install that I think is relevant

```
810 silly postinstall mongodb-prebuilt@5.0.6 /var/www/mediamade/node_modules/.staging/mongodb-prebuilt-a312066b
811 info lifecycle mongodb-prebuilt@5.0.6~postinstall: mongodb-prebuilt@5.0.6
812 verbose lifecycle mongodb-prebuilt@5.0.6~postinstall: unsafe-perm in lifecycle true
813 verbose lifecycle mongodb-prebuilt@5.0.6~postinstall: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/var/www/mediamade/node_modules/mongodb-prebuilt/node_modules/.bin:/var/www/mediamade/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
814 verbose lifecycle mongodb-prebuilt@5.0.6~postinstall: CWD: /var/www/mediamade/node_modules/mongodb-prebuilt
815 silly lifecycle mongodb-prebuilt@5.0.6~postinstall: Args: [ '-c', 'node install.js' ]
816 silly lifecycle mongodb-prebuilt@5.0.6~postinstall: Returned: code: 137  signal: null
817 info lifecycle mongodb-prebuilt@5.0.6~postinstall: Failed to exec postinstall script
818 verbose unlock done using /home/vagrant/.npm/_locks/staging-a1ac5c2642b54e9e.lock for /var/www/mediamade/node_modules/.staging
819 silly rollbackFailedOptional Starting
820 silly rollbackFailedOptional Finishing
821 silly runTopLevelLifecycles Starting
822 silly runTopLevelLifecycles Finishing
823 silly install printInstalled
824 warn optional Skipping failed optional dependency /chokidar/fsevents:
825 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.14
826 verbose stack Error: mongodb-prebuilt@5.0.6 postinstall: `node install.js`
826 verbose stack Exit status 137
826 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
826 verbose stack     at emitTwo (events.js:106:13)
826 verbose stack     at EventEmitter.emit (events.js:191:7)
826 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
826 verbose stack     at emitTwo (events.js:106:13)
826 verbose stack     at ChildProcess.emit (events.js:191:7)
826 verbose stack     at maybeClose (internal/child_process.js:877:16)
826 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
827 verbose pkgid mongodb-prebuilt@5.0.6
828 verbose cwd /var/www/mediamade
829 error Linux 3.13.0-95-generic
830 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--no-bin-links" "mongodb-prebuilt"
831 error node v6.7.0
832 error npm  v3.10.3
833 error code ELIFECYCLE
834 error mongodb-prebuilt@5.0.6 postinstall: `node install.js`
834 error Exit status 137
835 error Failed at the mongodb-prebuilt@5.0.6 postinstall script 'node install.js'.
835 error Make sure you have the latest version of node.js and npm installed.
835 error If you do, this is most likely a problem with the mongodb-prebuilt package,
835 error not with npm itself.
835 error Tell the author that this fails on your system:
835 error     node install.js
835 error You can get information on how to open an issue for this project with:
835 error     npm bugs mongodb-prebuilt
835 error Or if that isn't available, you can get their info via:
835 error     npm owner ls mongodb-prebuilt
835 error There is likely additional logging output above.
836 verbose exit [ 1, true ]
```

**Comment by winfinit** [comment]
can anyone please attempt same thing with latest release? your help and feedback would be greatly appreciated.

**Comment by vibhas77** [comment]
I am also getting the same error, any fix found?

**Comment by winfinit** [comment]
@vibhas77 there is no post install anymore with 7.x release, please post your logs

**Comment by vibhas77** [comment]
@winfinit Hi, I have resolved that issue. It was a missing package issue.
