### ISSUE TITLE
Strict mode SyntaxError in mongodb-prebuilt when using Mockgoose

### ISSUE THREAD

**Issue by vanb** [winfinit/mongodb-prebuilt#4]
It appears the author here is a contributor to mockgoose. When requiring mockgoose and wrapping mongoose, a syntax error is immediately thrown by this dependency. "In strict mode code, functions can only be declared at top level or immediately within another function."

Environment: node v0.12.4, mockgoose ^5.0.0-rc.4, mongodb-prebuilt ^4.1.5
- Example Code

```
var mongoose = require('mongoose');
var mockgoose = require('mockgoose');
mockgoose(mongoose);
```
- Error

```
Message:
    /Users/vanb/projects/qblu/after-notifications/node_modules/mockgoose/node_modules/mongodb-prebuilt/index.js:72
            function shutdown() {
            ^^^^^^^^
In strict mode code, functions can only be declared at top level or immediately within another function.
Stack:
/Users/vanb/projects/qblu/after-notifications/node_modules/mockgoose/node_modules/mongodb-prebuilt/index.js:72
            function shutdown() {
            ^^^^^^^^
SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/vanb/projects/qblu/after-notifications/node_modules/mockgoose/Mockgoose.js:3:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/vanb/projects/qblu/after-notifications/test/notification-hub.spec.js:8:17)
    at Module._compile (module.js:460:26)
```

**Comment by winfinit** [comment]
thank you for this report, new versions of Mockgoose(5.0.0-rc.5) and mongodb-prebuilt(4.2.6) were published,

**Comment by vanb** [comment]
Thanks so much for the rapid fix!
